export const CREAR_USUARIO = 'CREAR_USUARIO';
export const OBTENER_USUARIO = 'OBTENER_USUARIO';
export const WELCOME_USUARIO = 'WELCOME_USUARIO';
export const EDITAR_USUARIO = 'EDITAR_USUARIO';
export const BORRAR_USUARIO = 'BORRAR_USUARIO';
export const AUTENTICAR_USUARIO = 'AUTENTICAR_USUARIO';

export const CREAR_PERSONAL = 'CREAR_PERSONAL';
export const OBTENER_PERSONAL = 'OBTENER_PERSONAL';
export const EDITAR_PERSONAL = 'EDITAR_PERSONAL';
export const BORRAR_PERSONAL = 'BORRAR_PERSONAL'; 

export const CREAR_ADMINS = 'CREAR_ADMINS';
export const OBTENER_ADMINS = 'OBTENER_ADMINS';
export const EDITAR_ADMINS = 'EDITAR_ADMINS';
export const BORRAR_ADMINS = 'BORRAR_ADMINS';

export const CREAR_PROFESORES = 'CREAR_PROFESORES';
export const OBTENER_PROFESORES = 'OBTENER_PROFESORES';
export const EDITAR_PROFESORES = 'EDITAR_PROFESORES';
export const BORRAR_PROFESORES = 'BORRAR_PROFESORES';

export const CREAR_ESTUDIANTES = 'CREAR_ESTUDIANTES';
export const OBTENER_ESTUDIANTES = 'OBTENER_ESTUDIANTES';
export const EDITAR_ESTUDIANTES = 'EDITAR_ESTUDIANTES';
export const BORRAR_ESTUDIANTES = 'BORRAR_ESTUDIANTES'; 

export const CREAR_CURSOS = 'CREAR_CURSOS';
export const OBTENER_CURSOS = 'OBTENER_CURSOS';
export const EDITAR_CURSOS = 'EDITAR_CURSOS';
export const BORRAR_CURSOS = 'BORRAR_CURSOS'; 

export const CREAR_SEDES = 'CREAR_SEDES';
export const OBTENER_SEDES = 'OBTENER_SEDES';
export const EDITAR_SEDES = 'EDITAR_SEDES';
export const BORRAR_SEDES = 'BORRAR_SEDES'; 

export const CREAR_MATRICULA = 'CREAR_MATRICULA';
export const OBTENER_MATRICULA = 'OBTENER_MATRICULA';
export const EDITAR_MATRICULA = 'EDITAR_MATRICULA';
export const BORRAR_MATRICULA = 'BORRAR_MATRICULA'; 

export const CREAR_ASISTENCIA = 'CREAR_ASISTENCIA';
export const OBTENER_ASISTENCIA = 'OBTENER_ASISTENCIA';
export const EDITAR_ASISTENCIA = 'EDITAR_ASISTENCIA';
export const BORRAR_ASISTENCIA = 'BORRAR_ASISTENCIA'; 